name = "github-star-counter-dev"
type = "webpack"
account_id = "i33ealibxfdvhh33b5zvr0e3nuabcyq0"
workers_dev = true
zone_id = ""
webpack_config = "webpack.config.js"

[env.staging]
name = "my-worker-staging"

[env.production]
name = "github-star-counter"
