name = "api-dev"
type = "webpack"
account_id = "3ea01693f23309397d4b82c5e57b0e40"
workers_dev = true
zone_id = ""
webpack_config = "webpack.config.js"

[env.staging]
name = "my-worker-staging"

[env.production]
name = "api"
