name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci

      - run: npm run build --if-present
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - run: npm test
        env:
          CI: true

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: npm run build --if-present
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        env:
          NPM_CONFIG_LEGACY_PEER_DEPS: true
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          environment: 'production'
